package com.bather.philippa.peopledb.repository;

import com.bather.philippa.peopledb.model.Person;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.*;


public class PeopleRepositoryTests {

    private Connection connection;
    private PeopleRepository repo;

    @BeforeEach
    void setUp() throws SQLException{
        connection = DriverManager.getConnection("jdbc:h2:~/OneDrive/Desktop/PeopleDB/peaopledb".replace("~", System.getProperty("user.home")));
        connection.setAutoCommit(false);  // turn off auto-commits so that the test commits aren't persisted in the DB
        repo = new PeopleRepository(connection);
    }

    @AfterEach
    void tearDown() throws SQLException {
        // if connection failed, then connection would be null and there would be nothing too close
        if (connection != null) {
            connection.close();
        }
    }

    @Test
    public void canSaveOnePerson() throws SQLException {
        setUp();
        // DB code will live inside the repo
        Person person = new Person("John", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6")));
        // assert that on calling the save method, we receive an object and that object will now have an id
        // that id will be generated by the DB
        Person savedPerson = repo.save(person);
        assertThat(savedPerson.getId()).isGreaterThan(0);
    }

    @Test
    public void canSaveTwoPeople() throws SQLException {
        setUp();
        Person person1 = new Person("John", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6")));
        Person person2 = new Person("Bobby", "Smith", ZonedDateTime.of(1982, 3, 5, 20, 15, 0, 0, ZoneId.of("-6")));
        Person savedPerson1 = repo.save(person1);
        Person savedPerson2 = repo.save(person2);
        assertThat(savedPerson1.getId()).isNotEqualTo(savedPerson2.getId());
    }

    @Test
    public void canFindPersonById() {
        // i) insert known test data
        Person savedPerson = repo.save(new Person("Mary", "Clarence", ZonedDateTime.now()));
        // ii) find person by that known id
        Person foundPerson = repo.findById(savedPerson.getId()).get();
        assertThat(foundPerson).isEqualTo(savedPerson);
        // iii) clear DB
    }

    @Test
    public void canFindAll() {
        repo.save(new Person("John", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6"))));
        repo.save(new Person("John1", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6"))));
        repo.save(new Person("John2", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6"))));
        repo.save(new Person("John3", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6"))));
        repo.save(new Person("John4", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6"))));
        repo.save(new Person("John5", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6"))));
        repo.save(new Person("John6", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6"))));
        repo.save(new Person("John7", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6"))));
        repo.save(new Person("John8", "Smith", ZonedDateTime.of(1980, 11, 15, 15, 15, 0, 0, ZoneId.of("-6"))));
        List<Person> people = repo.findAll();
        assertThat(people.size()).isGreaterThanOrEqualTo(9);
    }

    @Test
    public void testPersonIdNotFound() {
        // optionals better than returning null and potentially better than throwing an exception (unwieldy)
        Optional<Person> foundPerson = repo.findById(-1L);
        assertThat(foundPerson).isEmpty();
    }

    @Test
    public void canGetCount() {
        long startCount = repo.count();
        repo.save(new Person ("John", "Smith", ZonedDateTime.of(1997, 11, 15, 15, 15, 15, 15, ZoneId.of ("+6"))));
        repo.save(new Person ("Zoe", "Smith", ZonedDateTime.of(1997, 11, 15, 15, 15, 15, 15, ZoneId.of ("+6"))));
        long endCount = repo.count();
        assertThat(endCount).isEqualTo(startCount + 2);
    }

    @Test
    public void canDelete() {
        // 1. insert record in
        Person person = repo.save(new Person ("Max", "Million", ZonedDateTime.of(1987, 11, 15, 15, 15, 15, 15, ZoneId.of ("+6"))));
        // 2. get count
        long startCount = repo.count();
        // 3. delete record
        repo.delete(person);
        // 4. get count
        long endCount = repo.count();
        assertThat(endCount).isEqualTo(startCount - 1);
    }

    @Test
    public void canDeleteMultiplePeople() {
        // i) insert two people into DB
        Person p1 = repo.save(new Person ("John", "Smith", ZonedDateTime.of(1997, 11, 15, 15, 15, 15, 15, ZoneId.of ("+6"))));
        Person p2 = repo.save(new Person ("Zoe", "Smith", ZonedDateTime.of(1997, 11, 15, 15, 15, 15, 15, ZoneId.of ("+6"))));
        long startCount = repo.count();
        repo.delete(p1, p2);
        long endCount = repo.count();
        assertThat(endCount).isEqualTo(startCount - 2);
      }

    @Test
    public void canUpdate() {
        // 1. create person
        Person savedPerson = repo.save(new Person ("John", "Smith", ZonedDateTime.of(1997, 11, 15, 15, 15, 15, 15, ZoneId.of ("+6"))));
        // 2. retrieve person: before changes
        Person p1 = repo.findById(savedPerson.getId()).get();
        // 3. update salary
        savedPerson.setSalary(new BigDecimal("73000.74"));
        repo.update(savedPerson);
        // 4. retrieve person again from the database
        Person p2 = repo.findById(savedPerson.getId()).get();
        // 5. inequality as p1 object is that retrieved before changes were made, which are reflected in the p2 object
        assertThat(p2.getSalary()).isNotEqualTo(p1.getSalary());
    }

    //    @Test
//    public void experiment() {
//        Person p1 = new Person(10L, null, null, null);
//        Person p2 = new Person(20L, null, null, null);
//        Person p3 = new Person(30L, null, null, null);
//        Person p4 = new Person(40L, null, null, null);
//        Person p5 = new Person(50L, null, null, null);
//
//        Person[] people = Arrays.asList(p1,p2,p3,p4,p5).toArray(new Person[]{});
//        // strings API to convert array of people to string of ids delimited by a comma
//        // can't use the API on array, so convert to collections
//        // convert array of persons to stream of persons
//        // which then gets converted to a stream of longs
//        // convert longs to string
//        String ids = Arrays.stream(people).map(Person::getId).map(String::valueOf).collect(joining(","));
//        System.out.println(ids);
//    }
}
