package com.bather.philippa.peopledb.repository;

import com.bather.philippa.peopledb.exception.UnableToFindByIDException;
import com.bather.philippa.peopledb.exception.UnableToSaveException;
import com.bather.philippa.peopledb.model.Entity;

import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import static java.util.stream.Collectors.joining;

public abstract class CrudRepositoryNoReflectionsAPI<T extends Entity> {

    protected Connection connection; // protected so can be seen by subclasses in package

    public CrudRepositoryNoReflectionsAPI(Connection connection) {
        this.connection = connection;
    }

    public T save(T entity) throws UnableToSaveException {
        try {
            // second arg to return generated key
            PreparedStatement ps = connection.prepareStatement(getSaveSql(), Statement.RETURN_GENERATED_KEYS);
            mapForSave(entity, ps);
            int recordsAffected = ps.executeUpdate();
            // need autogenerated id, assuming correct
            ResultSet rs = ps.getGeneratedKeys();  // ResultSet like a 2D array (rows and col, like a spreadsheet), similar to an iterator (.next())
            while (rs.next()) {
                long id = rs.getLong(1); // get first column back
                entity.setId(id);
                System.out.println(entity);
            }
            System.out.format("Records affected: %d%n", recordsAffected);
        } catch (SQLException e){
            e.printStackTrace();
            // not nec to declare in the signature as a runtime exception
            // but better practice to do so for documentation
            throw new UnableToSaveException("Tried to save entity: " + entity);
        }
        return entity;
    }

    public Optional<T> findById(long id) throws UnableToFindByIDException {
        T entity = null;
        try {
            PreparedStatement ps = connection.prepareStatement(getFindByIdSql());
            ps.setLong(1, id);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                entity = extractEntityFromResultSet(rs);
            }
        } catch (SQLException e) {
            throw new UnableToFindByIDException("Unable to find entity for id: " + id);
        }
        // allows a null person or non-null person to be passed to avoid pot exceptions being thrown
        return Optional.ofNullable(entity);
    }

    public List<T> findAll() throws RuntimeException {
        List<T> entities = new ArrayList<>();
        try {
            PreparedStatement ps = connection.prepareStatement(getFindAllSql());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                entities.add(extractEntityFromResultSet(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException();
        }
        return entities;
    }

    public long count() {
        long count = 0;
        try {
            PreparedStatement ps = connection.prepareStatement(getCountIdSql());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                // or, if ps SELECT COUNT(ID) FROM TABLE, the columnLabel would be 1
                count = rs.getLong("COUNT");
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return count;
    }

    public void delete(T entity) {
        try {
            PreparedStatement ps = connection.prepareStatement(getDeleteRecordSql());
            ps.setLong(1, entity.getId());
            int affectedRecordCount = ps.executeUpdate();
            System.out.println(affectedRecordCount);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void delete(T ...entities) {
        // 1. method 1: less efficient as separate and distinct updates for each person, i.e. makes multiple calls
//        for (T entity : entities) {
//            delete(entity);
//        }
        // 2. method 2: deleting multiple records simultaneously; more efficient as only one call to the DB; danger SQL injection attack
        try {
            // H2 DB doesn't have support for Prepared Statement with method 2 technique
            Statement stmt = connection.createStatement();
            String ids = Arrays.stream(entities).map(T::getId).map(String::valueOf).collect(joining(","));
            int affectedRecordCount = stmt.executeUpdate(getDeleteNRecordsSql().replace(":ids", ids));
            System.out.println(affectedRecordCount);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void update(T entity) {
        try {
            PreparedStatement ps = connection.prepareStatement(getUpdateSql());
            mapForUpdate(entity, ps);
            ps.setLong(5, entity.getId());
            int affectedRecords = ps.executeUpdate();
            System.out.println(affectedRecords);
        } catch(SQLException e) {
            throw new RuntimeException(e);
        }
    }

    abstract void mapForUpdate(T entity, PreparedStatement ps) throws SQLException;

    abstract void mapForSave(T entity, PreparedStatement ps) throws SQLException;
    abstract T extractEntityFromResultSet(ResultSet rs) throws SQLException;

    protected abstract String getSaveSql();

    /**
     * @return Returns a String that represents a SQL needed to retrieve one entity.
     * The SQL must contain one SQL parameter, i.e. "?", that will bind to the
     * entity's ID.
     */
    abstract String getFindByIdSql();
    abstract String getFindAllSql();
    protected abstract String getCountIdSql();
    protected abstract String getDeleteRecordSql();

    /**
     * @return Returns a SQL String like: "DELETE FROM PEOPLE WHERE ID IN (:ids)".
     * Be sure to include the "(:ids)" name parameter and call it "ids".
     */
    protected abstract String getDeleteNRecordsSql();
    protected abstract String getUpdateSql();
}
