package com.bather.philippa.peopledb.repository;

import com.bather.philippa.peopledb.annotation.Id;
import com.bather.philippa.peopledb.annotation.MultiSQL;
import com.bather.philippa.peopledb.annotation.SQL;
import com.bather.philippa.peopledb.exception.NoIDFoundException;
import com.bather.philippa.peopledb.exception.UnableToFindByIDException;
import com.bather.philippa.peopledb.exception.UnableToSaveException;
import com.bather.philippa.peopledb.model.CrudOperation;

import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;
import java.util.stream.Stream;

import static java.util.stream.Collectors.joining;

public abstract class CrudRepository<T> {

    protected Connection connection; // protected so can be seen by subclasses in package

    public CrudRepository(Connection connection) {
        this.connection = connection;
    }

    public T save(T entity) throws UnableToSaveException {
        try {
            // second arg to return generated key
            PreparedStatement ps = connection.prepareStatement(getSqlByAnnotation(CrudOperation.SAVE, this::getSaveSql), Statement.RETURN_GENERATED_KEYS);
            mapForSave(entity, ps);
            int recordsAffected = ps.executeUpdate();
            // need autogenerated id, assuming correct
            ResultSet rs = ps.getGeneratedKeys();  // ResultSet like a 2D array (rows and col, like a spreadsheet), similar to an iterator (.next())
            while (rs.next()) {
                long id = rs.getLong(1); // get first column back
                setIdByAnnotation(id, entity);
                postSave(entity, id);
            }
//            System.out.format("Records affected: %d%n", recordsAffected);
        } catch (SQLException e){
            e.printStackTrace();
            // not nec to declare in the signature as a runtime exception
            // but better practice to do so for documentation
            throw new UnableToSaveException("Tried to save entity: " + entity);
        }
        return entity;
    }

    public Optional<T> findById(long id) throws UnableToFindByIDException {
        T entity = null;
        try {
            PreparedStatement ps = connection.prepareStatement(getSqlByAnnotation(CrudOperation.FIND_BY_ID, this::getFindByIdSql));
            ps.setLong(1, id);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                entity = extractEntityFromResultSet(rs);
            }
        } catch (SQLException e) {
            throw new UnableToFindByIDException("Unable to find entity for id: " + id);
        }
        // allows a null person or non-null person to be passed to avoid pot exceptions being thrown
        return Optional.ofNullable(entity);
    }

    public List<T> findAll() throws RuntimeException {
        List<T> entities = new ArrayList<>();
        try {
            PreparedStatement ps = connection.prepareStatement(getSqlByAnnotation(CrudOperation.FIND_ALL, this::getFindAllSql));
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                entities.add(extractEntityFromResultSet(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException();
        }
        return entities;
    }

    public long count() {
        long count = 0;
        try {
            PreparedStatement ps = connection.prepareStatement(getSqlByAnnotation(CrudOperation.COUNT, this::getCountIdSql));
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                count = rs.getLong("COUNT");
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return count;
    }

    public void delete(T entity) {
        try {
            PreparedStatement ps = connection.prepareStatement(getSqlByAnnotation(CrudOperation.DELETE_ONE, this::getDeleteRecordSql));
            ps.setLong(1, getIdByAnnotation(entity));
            int affectedRecordCount = ps.executeUpdate();
            System.out.println(affectedRecordCount);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private Long getIdByAnnotation(T entity) {
        return Arrays.stream(entity.getClass().getDeclaredFields()) // convert array of fields into stream of fields
                .filter(f -> f.isAnnotationPresent(Id.class))
                .map(f -> {
                    f.setAccessible(true);  // override id's private access modifier
                    Long id = null;
                    try {
                        id = (Long) f.get(entity);
                    } catch (IllegalAccessException e) {
                        throw new RuntimeException(e);
                    }
                    return id;
                })
                .findFirst().orElseThrow(() -> new NoIDFoundException("No ID annotated field found."));
    }

    private void setIdByAnnotation(Long id, T entity) {
        Arrays.stream(entity.getClass().getDeclaredFields())
                .filter(f -> f.isAnnotationPresent(Id.class))
                .forEach(f -> {
                    f.setAccessible(true);
                    try {
                        f.set(entity, id);
                    } catch (IllegalAccessException e) {
                        throw new RuntimeException("Unable to set ID field value");
                    }
                });
    }

    public void delete(T ...entities) {
        // 1. method 1: less efficient as separate and distinct updates for each person, i.e. makes multiple calls
//        for (T entity : entities) {
//            delete(entity);
//        }
        // 2. method 2: deleting multiple records simultaneously; more efficient as only one call to the DB; danger SQL injection attack
        try {
            // H2 DB doesn't have support for Prepared Statement with method 2 technique
            Statement stmt = connection.createStatement();
            String ids = Arrays.stream(entities).map(e -> getIdByAnnotation(e)).map(String::valueOf).collect(joining(","));
            int affectedRecordCount = stmt.executeUpdate(getSqlByAnnotation(CrudOperation.DELETE_MANY, this::getDeleteNRecordsSql).replace(":ids", ids));
            System.out.println(affectedRecordCount);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void update(T entity) {
        try {
            PreparedStatement ps = connection.prepareStatement(getSqlByAnnotation(CrudOperation.UPDATE, this::getUpdateSql));
            mapForUpdate(entity, ps);
            ps.setLong(5, getIdByAnnotation(entity));
            int affectedRecords = ps.executeUpdate();
            System.out.println(affectedRecords);
        } catch(SQLException e) {
            throw new RuntimeException(e);
        }
    }

    abstract void mapForUpdate(T entity, PreparedStatement ps) throws SQLException;

    abstract void mapForSave(T entity, PreparedStatement ps) throws SQLException;
    abstract T extractEntityFromResultSet(ResultSet rs) throws SQLException;

    private String getSqlByAnnotation(CrudOperation operationType, Supplier<String> sqlGetter) {
        Stream<SQL> multiSqlStream = Arrays.stream(this.getClass().getDeclaredMethods())
                .filter(m -> m.isAnnotationPresent(MultiSQL.class))
                .map(m -> m.getAnnotation(MultiSQL.class))
                .flatMap(msql -> Arrays.stream(msql.value())); // flat map to flatten streams of streams to one

        Stream<SQL> sqlStream = Arrays.stream(this.getClass().getDeclaredMethods())
                .filter(m -> m.isAnnotationPresent(SQL.class)) //
                .map(m -> m.getAnnotation(SQL.class)); // and that method has the specified annotation class

        return Stream.concat(multiSqlStream, sqlStream)
                .filter(a -> a.operationType().equals(operationType))
                .map(SQL::value) // and there is a value, get it
                .findFirst()// returns an optional, which would be empty if it doesn't exist
                .orElseGet(sqlGetter); // else get method reference to the required method
    }

    protected String getSaveSql() { throw new RuntimeException("SQL not defined.");}
    protected void postSave(T entity, long id) { }

    /**
     * @return Returns a String that represents a SQL needed to retrieve one entity.
     * The SQL must contain one SQL parameter, i.e. "?", that will bind to the
     * entity's ID.
     */
    protected String getFindByIdSql() { throw new RuntimeException("SQL not defined.");}
    protected String getFindAllSql() { throw new RuntimeException("SQL not defined.");}
    protected String getCountIdSql() { throw new RuntimeException("SQL not defined.");}
    protected String getDeleteRecordSql() { throw new RuntimeException("SQL not defined.");}

    /**
     * @return Returns a SQL String like: "DELETE FROM PEOPLE WHERE ID IN (:ids)".
     * Be sure to include the "(:ids)" name parameter and call it "ids".
     */
    protected String getDeleteNRecordsSql() { throw new RuntimeException("SQL not defined.");}
    protected String getUpdateSql() { throw new RuntimeException("SQL not defined.");}
}
